services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - matcha_pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: matcha_db
      POSTGRES_USER: matcha_user
      POSTGRES_PASSWORD: msp
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U matcha_user -d matcha_db"]
      interval: 2s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  matcha_pg_data:
